@api = http://localhost:3000

GET {{api}}/workers

###
GET {{api}}/workers/54664848

###
POST {{api}}/workers
Content-Type: application/json

{
    "dni":1076624748,
    "name":"Miguel Camacho"
}

###
DELETE {{api}}/workers/10766123

###
PUT {{api}}/workers/649845
Content-Type: application/json

{
    "name":"Usuario prueba numero"
}


