export const responseCodes = {
    COD_RESPONSE_SUCCESS: 0,
    COD_RESPONSE_ERROR_CREATE: 1001,
    COD_RESPONSE_ERROR_UPDATE: 1002,
    COD_RESPONSE_ERROR_DELETE: 1003,
    COD_RESPONSE_ERROR_LIST: 1005,
    COD_RESPONSE_ERROR_LOGIN: 1006,
}